apiVersion: v1
kind: Service
metadata:
  name: {{ (include "api-citas-pacientes.fullname" .) | printf "%s-service" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api-citas-pacientes.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "api-citas-pacientes.selectorLabels" . | nindent 4 }}
